import argparse
from pathlib import Path
import re
import sys

import yaml

from .records import Category, Record, RepositorySnapshot, load_repository


_GENERATED_NOTICE = "<!-- Generated by python -m qol_kb.views. Do not edit. -->"
_TOPIC_METADATA_PREFIXES = (
    "**Categories:**",
    "**Evidence:**",
    "**Applicability:**",
    "**Support mode:**",
    "**Status:**",
)


def _markdown_cell(value: object) -> str:
    return str(value).replace("\\", "\\\\").replace("|", "\\|").replace("\r", " ").replace("\n", " ")


def _record_id_key(record: Record) -> tuple[str, int]:
    prefix, number = record.front_matter["id"].split("-", maxsplit=1)
    return prefix, int(number)


def _identity_key(identity: str) -> tuple[str, int]:
    prefix, number = identity.split("-", maxsplit=1)
    return prefix, int(number)


def _partition_by_status(records: tuple[Record, ...]) -> tuple[tuple[Record, ...], tuple[Record, ...]]:
    active = tuple(sorted((record for record in records if record.front_matter["status"] == "Active"), key=_record_id_key))
    deprecated = tuple(sorted((record for record in records if record.front_matter["status"] == "Deprecated"), key=_record_id_key))
    return active, deprecated


def _partition_categories(categories: tuple[Category, ...]) -> tuple[tuple[Category, ...], tuple[Category, ...]]:
    active = tuple(sorted((category for category in categories if category.status == "Active"), key=lambda category: category.name))
    deprecated = tuple(sorted((category for category in categories if category.status == "Deprecated"), key=lambda category: category.name))
    return active, deprecated


def _item_reference_ids(record: Record) -> tuple[str, ...]:
    references = {
        reference_id
        for claim in record.front_matter["evidence_claims"]
        for reference_id in claim["references"]
    }
    return tuple(sorted(references, key=_identity_key))


def _table(headers: tuple[str, ...], rows: list[tuple[str, ...]], empty: str) -> list[str]:
    if not rows:
        return [empty]
    return [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
        *("| " + " | ".join(row) + " |" for row in rows),
    ]


def render_catalog(snapshot: RepositorySnapshot) -> str:
    active_categories, deprecated_categories = _partition_categories(snapshot.categories)
    active_items, deprecated_items = _partition_by_status(snapshot.items)
    sections = [_GENERATED_NOTICE, "", "## Active Categories"]
    sections.extend(_table(
        ("Category", "Definition"),
        [(_markdown_cell(category.name), _markdown_cell(category.definition)) for category in active_categories],
        "No Active categories.",
    ))
    sections.extend(["", "## Deprecated Categories"])
    sections.extend(_table(
        ("Category", "Definition", "Replaced by"),
        [(_markdown_cell(category.name), _markdown_cell(category.definition), _markdown_cell(category.replaced_by or "")) for category in deprecated_categories],
        "No Deprecated categories.",
    ))
    sections.extend(["", "## Active QoL Items"])
    sections.extend(_table(
        ("ID", "Statement", "Kind", "Categories", "Evidence Strength", "Applicability", "Support mode", "References"),
        [
            (
                f"[{record.front_matter['id']}](../items/{record.front_matter['id']}.md)",
                _markdown_cell(record.front_matter["statement"]),
                _markdown_cell(record.front_matter["kind"]),
                _markdown_cell(", ".join(record.front_matter["categories"])),
                _markdown_cell(record.evidence_strength or ""),
                _markdown_cell(record.front_matter["applicability"]),
                _markdown_cell(record.front_matter["support_mode"]),
                ", ".join(f"[{reference_id}](references.md#{reference_id.lower()})" for reference_id in _item_reference_ids(record)),
            )
            for record in active_items
        ],
        "No Active QoL items.",
    ))
    sections.extend(["", "## Deprecated QoL Items"])
    sections.extend(_table(
        ("ID", "Statement", "Deprecation reason", "Replaced by"),
        [
            (
                f"[{record.front_matter['id']}](../items/{record.front_matter['id']}.md)",
                _markdown_cell(record.front_matter["statement"]),
                _markdown_cell(record.front_matter.get("deprecation_reason") or ""),
                ", ".join(f"[{identity}](../items/{identity}.md)" for identity in sorted(record.front_matter.get("replaced_by", []), key=_identity_key)),
            )
            for record in deprecated_items
        ],
        "No Deprecated QoL items.",
    ))
    return "\n".join(sections) + "\n"


def _reference_entry(record: Record) -> list[str]:
    metadata = record.front_matter
    year = "Unknown" if metadata["year"] is None else metadata["year"]
    lines = [
        f"### {metadata['id']}",
        "",
        f"[Canonical record](../references/{metadata['id']}.md)",
        "",
        f"- **Title:** {_markdown_cell(metadata['title'])}",
        f"- **Authors:** {_markdown_cell(', '.join(metadata['authors']))}",
        f"- **Year:** {_markdown_cell(year)}",
        f"- **Source:** {_markdown_cell(metadata['source'])}",
        f"- **Source type:** {_markdown_cell(metadata['source_type'])}",
    ]
    for label, field in (("Design", "design"), ("DOI", "doi"), ("PMID", "pmid")):
        if metadata.get(field) is not None:
            lines.append(f"- **{label}:** {_markdown_cell(metadata[field])}")
    lines.extend(["- **URLs:**", *(f"  - {_markdown_cell(url)}" for url in metadata["urls"]), "- **Supports:**"])
    lines.extend(f"  - {_markdown_cell(boundary)}" for boundary in metadata["supports"])
    if metadata["status"] == "Deprecated":
        lines.append(f"- **Deprecation reason:** {_markdown_cell(metadata.get('deprecation_reason') or '')}")
        replacement = metadata.get("replaced_by")
        if replacement is not None:
            lines.append(f"- **Replaced by:** [{replacement}](#{replacement.lower()})")
    return lines


def render_references(snapshot: RepositorySnapshot) -> str:
    active_references, deprecated_references = _partition_by_status(snapshot.references)
    sections = [_GENERATED_NOTICE, "", "## Active References"]
    if active_references:
        for index, record in enumerate(active_references):
            if index:
                sections.append("")
            sections.extend(_reference_entry(record))
    else:
        sections.append("No Active references.")
    sections.extend(["", "## Deprecated References"])
    if deprecated_references:
        for index, record in enumerate(deprecated_references):
            if index:
                sections.append("")
            sections.extend(_reference_entry(record))
    else:
        sections.append("No Deprecated references.")
    return "\n".join(sections) + "\n"


def render_implementation_options(snapshot: RepositorySnapshot) -> str:
    active_options, deprecated_options = _partition_by_status(snapshot.implementation_options)
    sections = [_GENERATED_NOTICE, "", "## Active Implementation Options"]
    sections.extend(_table(
        ("ID", "Option", "Acquisition", "Implements"),
        [
            (
                f"[{record.front_matter['id']}](../implementation-options/{record.front_matter['id']}.md)",
                _markdown_cell(record.front_matter["name"]),
                _markdown_cell(record.front_matter["acquisition"]),
                ", ".join(
                    f"[{identity}](../items/{identity}.md)"
                    for identity in sorted(record.front_matter["implements"], key=_identity_key)
                ),
            )
            for record in active_options
        ],
        "No Active Implementation Options.",
    ))
    sections.extend(["", "## Deprecated Implementation Options"])
    sections.extend(_table(
        ("ID", "Option", "Deprecation reason", "Replaced by"),
        [
            (
                f"[{record.front_matter['id']}](../implementation-options/{record.front_matter['id']}.md)",
                _markdown_cell(record.front_matter["name"]),
                _markdown_cell(record.front_matter.get("deprecation_reason") or ""),
                ", ".join(
                    f"[{identity}](../implementation-options/{identity}.md)"
                    for identity in sorted(record.front_matter.get("replaced_by", []), key=_identity_key)
                ),
            )
            for record in deprecated_options
        ],
        "No Deprecated Implementation Options.",
    ))
    return "\n".join(sections) + "\n"


def _render_index_pointer(title: str, target: str, canonical_sources: str) -> str:
    return "\n".join(
        [
            _GENERATED_NOTICE,
            "",
            f"# {title}",
            "",
            f"This compatibility path is generated. Browse the current derived index at [{target}]({target}).",
            "",
            f"Canonical metadata is edited only in {canonical_sources}.",
        ]
    ) + "\n"


def render_catalog_pointer(_: RepositorySnapshot) -> str:
    return _render_index_pointer(
        "QoL Catalog",
        "generated/catalog.md",
        "`items/` and `categories.yaml`",
    )


def render_references_pointer(_: RepositorySnapshot) -> str:
    return _render_index_pointer(
        "Reference Index",
        "generated/references.md",
        "`references/`",
    )


def load_topic_selections(root: str | Path) -> dict[str, tuple[str, ...]]:
    path = Path(root) / "topic-views.yaml"
    try:
        raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    except yaml.YAMLError as error:
        raise ValueError(f"{path}: invalid YAML: {error}") from error

    topics = raw.get("topics") if isinstance(raw, dict) else None
    if not isinstance(topics, dict) or not topics:
        raise ValueError(f"{path}: topics must be a non-empty mapping")

    selections: dict[str, tuple[str, ...]] = {}
    for name, raw_identities in topics.items():
        if not isinstance(name, str) or Path(name).name != name or not name.endswith(".md"):
            raise ValueError(f"{path}: invalid topic filename {name!r}")
        if not isinstance(raw_identities, list) or not raw_identities:
            raise ValueError(f"{path}: {name} must select at least one QoL Item")
        identities = tuple(raw_identities)
        if any(
            not isinstance(identity, str)
            or re.fullmatch(r"QOL-[0-9]{3,}", identity) is None
            for identity in identities
        ):
            raise ValueError(f"{path}: {name} contains an invalid QoL Item identity")
        if len(set(identities)) != len(identities):
            raise ValueError(f"{path}: {name} contains duplicate QoL Item identities")
        selections[name] = identities
    return selections


def _topic_map(snapshot: RepositorySnapshot, identities: tuple[str, ...]) -> list[str]:
    items = {record.front_matter["id"]: record for record in snapshot.items}
    rows = []
    for identity in identities:
        if identity not in items:
            raise ValueError(f"topic view references unknown QoL Item {identity}")
        record = items[identity]
        references = ", ".join(
            f"[{reference_id}](../references/{reference_id}.md)"
            for reference_id in _item_reference_ids(record)
        )
        rows.append(
            (
                f"[{identity}](../items/{identity}.md)",
                _markdown_cell(record.front_matter["statement"]),
                _markdown_cell(record.front_matter["kind"]),
                _markdown_cell(", ".join(record.front_matter["categories"])),
                _markdown_cell(record.evidence_strength or ""),
                _markdown_cell(record.front_matter["applicability"]),
                _markdown_cell(record.front_matter["support_mode"]),
                _markdown_cell(record.front_matter["status"]),
                references,
            )
        )
    return _table(
        ("ID", "Statement", "Kind", "Categories", "Evidence Strength", "Applicability", "Support Mode", "Status", "References"),
        rows,
        "No QoL items selected for this topic.",
    )


def render_topic_view(source: str, snapshot: RepositorySnapshot, identities: tuple[str, ...]) -> str:
    lines = source.splitlines()
    try:
        map_heading = lines.index("## Map")
    except ValueError as error:
        raise ValueError("topic view is missing a '## Map' section") from error
    map_end = next(
        (index for index in range(map_heading + 1, len(lines)) if lines[index].startswith("## ")),
        len(lines),
    )
    replacement = ["## Map", "", *_topic_map(snapshot, identities), ""]
    lines[map_heading:map_end] = replacement
    lines = [
        line
        for line in lines
        if not line.startswith(_TOPIC_METADATA_PREFIXES)
    ]
    rendered = "\n".join(lines).rstrip() + "\n"
    rendered = re.sub(
        r"\.\./references\.md#ref-([0-9]{3,})",
        lambda match: f"../references/REF-{match.group(1)}.md",
        rendered,
        flags=re.IGNORECASE,
    )
    rendered = re.sub(
        r"\[(QOL-[0-9]{3,})\]\(\.\./catalog\.md(?:#[^)]+)?\)",
        lambda match: f"[{match.group(1)}](../items/{match.group(1)}.md)",
        rendered,
    )
    return rendered


OUTPUT_PATHS = {
    Path("catalog.md"): render_catalog_pointer,
    Path("references.md"): render_references_pointer,
    Path("generated/catalog.md"): render_catalog,
    Path("generated/references.md"): render_references,
    Path("generated/implementation-options.md"): render_implementation_options,
}


def generate_views(root: str | Path) -> dict[Path, bytes]:
    root_path = Path(root)
    snapshot = load_repository(root_path)
    generated = {
        relative_path: renderer(snapshot).encode("utf-8")
        for relative_path, renderer in OUTPUT_PATHS.items()
    }
    topics_path = root_path / "topics"
    if topics_path.is_dir():
        selections = load_topic_selections(root_path)
        topic_paths = {
            topic_path.name: topic_path
            for topic_path in sorted(topics_path.glob("*.md"))
        }
        if set(selections) != set(topic_paths):
            missing_selections = sorted(set(topic_paths) - set(selections))
            missing_topics = sorted(set(selections) - set(topic_paths))
            details = []
            if missing_selections:
                details.append(f"missing selections for {', '.join(missing_selections)}")
            if missing_topics:
                details.append(f"missing topic files for {', '.join(missing_topics)}")
            raise ValueError("topic view selection mismatch: " + "; ".join(details))
        for topic_name, identities in selections.items():
            topic_path = topic_paths[topic_name]
            relative_path = topic_path.relative_to(root_path)
            generated[relative_path] = render_topic_view(
                topic_path.read_text(encoding="utf-8"),
                snapshot,
                identities,
            ).encode("utf-8")
    return generated


def write_views(root: str | Path) -> None:
    root_path = Path(root)
    for relative_path, expected_bytes in generate_views(root_path).items():
        output_path = root_path / relative_path
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_bytes(expected_bytes)


def check_views(root: str | Path) -> tuple[Path, ...]:
    root_path = Path(root)
    expected = generate_views(root_path)
    return tuple(
        relative_path
        for relative_path, expected_bytes in expected.items()
        if not (root_path / relative_path).is_file()
        or (root_path / relative_path).read_bytes() != expected_bytes
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".", help="repository root")
    parser.add_argument("--check", action="store_true", help="check generated views for drift")
    args = parser.parse_args(argv)
    try:
        if args.check:
            drifted_paths = check_views(args.root)
            if drifted_paths:
                for relative_path in drifted_paths:
                    print(relative_path.as_posix(), file=sys.stderr)
                return 1
        else:
            write_views(args.root)
    except (OSError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
