from .records import Category, Record, RepositorySnapshot


_GENERATED_NOTICE = "<!-- Generated by python -m qol_kb.views. Do not edit. -->"


def _markdown_cell(value: object) -> str:
    return str(value).replace("\\", "\\\\").replace("|", "\\|").replace("\r", " ").replace("\n", " ")


def _record_id_key(record: Record) -> tuple[str, int]:
    prefix, number = record.front_matter["id"].split("-", maxsplit=1)
    return prefix, int(number)


def _identity_key(identity: str) -> tuple[str, int]:
    prefix, number = identity.split("-", maxsplit=1)
    return prefix, int(number)


def _partition_by_status(records: tuple[Record, ...]) -> tuple[tuple[Record, ...], tuple[Record, ...]]:
    active = tuple(sorted((record for record in records if record.front_matter["status"] == "Active"), key=_record_id_key))
    deprecated = tuple(sorted((record for record in records if record.front_matter["status"] == "Deprecated"), key=_record_id_key))
    return active, deprecated


def _partition_categories(categories: tuple[Category, ...]) -> tuple[tuple[Category, ...], tuple[Category, ...]]:
    active = tuple(sorted((category for category in categories if category.status == "Active"), key=lambda category: category.name))
    deprecated = tuple(sorted((category for category in categories if category.status == "Deprecated"), key=lambda category: category.name))
    return active, deprecated


def _item_reference_ids(record: Record) -> tuple[str, ...]:
    references = {
        reference_id
        for claim in record.front_matter["evidence_claims"]
        for reference_id in claim["references"]
    }
    return tuple(sorted(references, key=_identity_key))


def _table(headers: tuple[str, ...], rows: list[tuple[str, ...]], empty: str) -> list[str]:
    if not rows:
        return [empty]
    return [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
        *("| " + " | ".join(row) + " |" for row in rows),
    ]


def render_catalog(snapshot: RepositorySnapshot) -> str:
    active_categories, deprecated_categories = _partition_categories(snapshot.categories)
    active_items, deprecated_items = _partition_by_status(snapshot.items)
    sections = [_GENERATED_NOTICE, "", "## Active Categories"]
    sections.extend(_table(
        ("Category", "Definition"),
        [(_markdown_cell(category.name), _markdown_cell(category.definition)) for category in active_categories],
        "No Active categories.",
    ))
    sections.extend(["", "## Deprecated Categories"])
    sections.extend(_table(
        ("Category", "Definition", "Replaced by"),
        [(_markdown_cell(category.name), _markdown_cell(category.definition), _markdown_cell(category.replaced_by or "")) for category in deprecated_categories],
        "No Deprecated categories.",
    ))
    sections.extend(["", "## Active QoL Items"])
    sections.extend(_table(
        ("ID", "Statement", "Kind", "Categories", "Evidence Strength", "Applicability", "Support mode", "References"),
        [
            (
                f"[{record.front_matter['id']}](../items/{record.front_matter['id']}.md)",
                _markdown_cell(record.front_matter["statement"]),
                _markdown_cell(record.front_matter["kind"]),
                _markdown_cell(", ".join(record.front_matter["categories"])),
                _markdown_cell(record.evidence_strength or ""),
                _markdown_cell(record.front_matter["applicability"]),
                _markdown_cell(record.front_matter["support_mode"]),
                ", ".join(f"[{reference_id}](references.md#{reference_id.lower()})" for reference_id in _item_reference_ids(record)),
            )
            for record in active_items
        ],
        "No Active QoL items.",
    ))
    sections.extend(["", "## Deprecated QoL Items"])
    sections.extend(_table(
        ("ID", "Statement", "Deprecation reason", "Replaced by"),
        [
            (
                f"[{record.front_matter['id']}](../items/{record.front_matter['id']}.md)",
                _markdown_cell(record.front_matter["statement"]),
                _markdown_cell(record.front_matter.get("deprecation_reason") or ""),
                ", ".join(f"[{identity}](../items/{identity}.md)" for identity in sorted(record.front_matter.get("replaced_by", []), key=_identity_key)),
            )
            for record in deprecated_items
        ],
        "No Deprecated QoL items.",
    ))
    return "\n".join(sections) + "\n"


def _reference_entry(record: Record) -> list[str]:
    metadata = record.front_matter
    lines = [
        f"### {metadata['id']}",
        "",
        f"[Canonical record](../references/{metadata['id']}.md)",
        "",
        f"- **Title:** {_markdown_cell(metadata['title'])}",
        f"- **Authors:** {_markdown_cell(', '.join(metadata['authors']))}",
        f"- **Year:** {_markdown_cell(metadata['year'])}",
        f"- **Source:** {_markdown_cell(metadata['source'])}",
        f"- **Source type:** {_markdown_cell(metadata['source_type'])}",
    ]
    for label, field in (("Design", "design"), ("DOI", "doi"), ("PMID", "pmid")):
        if metadata.get(field) is not None:
            lines.append(f"- **{label}:** {_markdown_cell(metadata[field])}")
    lines.extend(["- **URLs:**", *(f"  - {_markdown_cell(url)}" for url in metadata["urls"]), "- **Supports:"])
    lines.extend(f"  - {_markdown_cell(boundary)}" for boundary in metadata["supports"])
    if metadata["status"] == "Deprecated":
        lines.append(f"- **Deprecation reason:** {_markdown_cell(metadata.get('deprecation_reason') or '')}")
        replacement = metadata.get("replaced_by")
        if replacement is not None:
            lines.append(f"- **Replaced by:** [{replacement}](#{replacement.lower()})")
    return lines


def render_references(snapshot: RepositorySnapshot) -> str:
    active_references, deprecated_references = _partition_by_status(snapshot.references)
    sections = [_GENERATED_NOTICE, "", "## Active References"]
    if active_references:
        for index, record in enumerate(active_references):
            if index:
                sections.append("")
            sections.extend(_reference_entry(record))
    else:
        sections.append("No Active references.")
    sections.extend(["", "## Deprecated References"])
    if deprecated_references:
        for index, record in enumerate(deprecated_references):
            if index:
                sections.append("")
            sections.extend(_reference_entry(record))
    else:
        sections.append("No Deprecated references.")
    return "\n".join(sections) + "\n"
